### ISSUE TITLE
Is this a dead project?

### ISSUE THREAD

**Issue by bordenc** [skarim/vobject#185]
Last commit was over 4 years ago (as of this writing), and this project should be updated for new versions of the standards. Unfortunately, a lot of downstream packages rely on this project, so 'fork and abandon' isn't so simple. The last known maintainer is @skarim. Can he assign a new maintainer if he's no longer willing or able to maintain the project?

**Comment by return42** [comment]
@skarim many projects are based on vobject, can you say what is the future of vobject?

**Comment by alqu** [comment]
Same here. Is this project still alive?

**Comment by pbiering** [comment]
There are some forks, potentially one can be elected to be the new master (if maintainer accepts) or a new fork has to be created by a team as successor.

**Comment by bigcat88** [comment]
Any news on this?

_It's very sad that a language like Python does not have normal library for vobject..._

**Comment by akuker** [comment]
@skarim - would it be possible to add additional maintainers to help pull in some of these changes/fixes? This is a great library and I'd love to see it continue to grow/evolve.

**Comment by bordenc** [comment]
Maybe we need to fork and go downstream to the distros and ask them to change their repo links?

I don't suppose GitHub has the capacity to force an ownership transfer when the original owner clearly has no more interest in the project?

**Comment by lucc** [comment]
The @eventable org where this project is located has no commit in any repository after 2018. It has https://www.eventable.com/developers configured as its homepage but that returns a 404 code.  The page https://www.eventable.com/ does exist but explains that "eventable has joined with addevent". What ever "joined" means in this context it looks like @AddEventInc is some kind of successor to @eventable.  Maybe they are stepping up?

**Comment by da4089** [comment]
I've reached out to both @skarim and @wpercy.

@wpercy has said that he's no longer responsible for vObject maintenance.  I haven't heard back from @skarim as yet.

If there's no signs of life shortly, I'd be interested in helping organize (and work on) a successor project.

**Comment by da4089** [comment]
> @wpercy has said that he's no longer responsible for vObject maintenance. I haven't heard back from @skarim as yet.

Still nothing from @skarim.

> If there's no signs of life shortly, I'd be interested in helping organize (and work on) a successor project.

Anyone else interested in setting this up?

**Comment by pbiering** [comment]
> Anyone else interested in setting this up?

Yes, because https://github.com/Kozea/Radicale is strongly depending on this.

**Comment by da4089** [comment]
I've created the https://github.com/py-vobject organization and forked the repo into https://github.com/py-vobject/vobject

@pbiering, I'll add you to the organization.

I'll try to make a start on merging some of the open PRs over the weekend.

I'd like to get access to the existing PyPI project: it appears as if @skarim, @wpercy, and the original author (Jeffrey Harris) are admins.  I got a response from @wpercy earlier, so hopefully he'll be willing to add new admins (or publish it himself) once we've got something worth releasing.

**Comment by da4089** [comment]
Anyone else who's willing to help out, please let me know.

**Comment by return42** [comment]
> I've created the https://github.com/py-vobject organization and forked the repo into https://github.com/py-vobject/vobject

Thanks a lot :+1: .. I follow the new project .. if I can help I will get in touch / will send my PR ... it is good to have a place where activities are worthwhile again ... I think the community will then become more active again.  Thanks again for your commitment :rocket:

**Comment by pbiering** [comment]
@da4089 : I've started labeling of "vobject" related issues in Radicale "Issues", perhaps one can pull some test cases from there to fix "vobject" or create workarounds for known broken client issues.

**Comment by da4089** [comment]
> @da4089 : I've started labeling of "vobject" related issues in Radicale "Issues", perhaps one can pull some test cases from there to fix "vobject" or create workarounds for known broken client issues.

Thanks @pbiering -- I'll prioritize getting those fixed, and pull what I can for testing.  This is great -- thanks again!

**Comment by akuker** [comment]
@da4089 - I'm also willing to help out. Feel free to let me know how I can help.

**Comment by dbarnett** [comment]
@da4089 all settled now, or could you still use more maintainers? I took over maintaining related https://github.com/insanum/gcalcli and would be happy to help maintain vobject too.
